show cli first cut implementation
project-safari/zebra pull request #110
Opened 2022-08-09 04:34 UTC by rchamarthy

Signed-off-by: Ravi Chamarthy <ravi@chamarthy.dev>

2022-08-09 17:26 UTC, chuckluv approved these changes

2022-08-09 21:03 UTC, shravyanandyala requested changes
I'm not sure if making store.Create() not enforce a group label is a good idea -- I understand it is necessary right now because "Resource" now encompasses User, etc. but perhaps we need to rethink this design choice. I'm afraid the leniency of our preconditions will result in developers abusing the system which can lead to many errors down the line.

2022-08-09 21:03 UTC, shravyanandyala commented on store/store_test.go
> +	dcd := dc.LabType()
Same as before, dcd is only used in this one place.

2022-08-09 21:05 UTC, rchamarthy commented on cmd/client/show.go
> +	if len(resTypes) == 0 {
Ah. I did not know that. I will make the change.

2022-08-09 21:07 UTC, rchamarthy commented on cmd/client/show.go
> +	showCmd.AddCommand(&cobra.Command{
I wanted to be explicit. In the standard RSA lingo Key means private key and public key is explicitly called a public key. We should never show the key actually but we do store it in user profile. Its the user's responsibility to secure it.

2022-08-09 21:07 UTC, rchamarthy commented on cmd/client/show.go
> +	cfgFile := cmd.Flag("config").Value.String()
will do. code climate also complained and I was thinking of fixing it :)

2022-08-09 21:08 UTC, rchamarthy commented on cmd/client/show.go
> +			if r, ok := resource.(*compute.Server); ok {
So we have a GetStatus. Perfect. we will move to that.

2022-08-09 21:09 UTC, rchamarthy commented on cmd/client/show.go
> +	showCmd.AddCommand(&cobra.Command{
I didnt get the suggestion. can you give me an example set of command references.

2022-08-09 21:10 UTC, rchamarthy commented on store/store.go
> +}
I wonder why we even have that lock/unlock if this function is a noop.

2022-08-09 21:11 UTC, rchamarthy commented on store/store_test.go
> +	some := network.VLANPoolType()
if its not used its supposed to be a compiler error actually.

2022-08-09 21:17 UTC, shravyanandyala commented on cmd/client/show.go
> +	showCmd.AddCommand(&cobra.Command{
Sure. I was thinking this:
```
zebra show resources
zebra show server
zebra show datacenter
zebra show vcenter
...
```
The reason I prefer this is because the user might think a command is ```zebra show esxs``` but it's really ```zebra show esxes```. Plurals can complicate the user experience. But, as I said before, this is just personal preference so feel free to ignore.

2022-08-09 21:20 UTC, shravyanandyala commented on store/store.go
> +}
It's probably passing the test cases the majority of the time -- but, we still risk a race condition because we are indeed modifying the store in some of the calling functions.

2022-08-09 21:22 UTC, shravyanandyala commented on store/store_test.go
> +	some := network.VLANPoolType()
It's used in the next line but just that once so that's probably why there's no explicit error. But personally I feel it's bad style, we can directly do ```factory.Add(network.VLANPoolType())``` and that's perfectly understandable code. I guess we can classify this as a nitpick but I feel strongly about enforcing some style rules including this.

2022-08-09 22:16 UTC, rchamarthy commented on cmd/client/show.go
> +	showCmd.AddCommand(&cobra.Command{
ok lets make this change. Your command names are at least not going to be tongue twisters.

2022-08-09 22:17 UTC, rchamarthy commented on store/store_test.go
> +	some := network.VLANPoolType()
this is a nitpick. I will leave it alone to the author's preference :)

2022-08-10 00:51 UTC, shravyanandyala commented on cmd/client/show.go
> +	showCmd.AddCommand(&cobra.Command{
Please re-read my previous comment, I mentioned sticking to any uniform convention. Since then, I've decided the singular convention is what I prefer. If you have reasons for why you think plural is better, feel free to express them. At the end of the day, user experience is the #1 priority so if that means making 50 or 5000 adjustments, we should gladly do it! Revisions do not stop the project from advancing -- they help it advance.

2022-08-10 02:29 UTC, rchamarthy commented on cmd/herd/main_test.go
> +	cmd := &cobra.Command{ //nolint:exhaustruct,exhaustivestruct
Fixed.

2022-08-10 02:37 UTC, rchamarthy commented on cmd/client/show.go
> +	showCmd.AddCommand(&cobra.Command{
@evaachim @shravyanandyala we must keep the discussions technical and focus on improving the product. In this particular case, I think the suggestion adds value, and there is precedence. I actually went and checked cisco NXOS CLI, and I see that there is a command called show interface, which displays all the interfaces.

@evaachim, if you feel strongly about plural, we add the plural form as an alias where it makes sense. As a team, we must allow each other to change our opinions and also value each other opinions. That is the only way we can make the product better. I will update the PR to use the singular form of commands as that seems to be your original intent as well.

Last, the back and forth is how we exchange ideas and build a strong consensus for the product choices. As long as it is not too disruptive, I would encourage it.

2022-08-10 23:44 UTC, rchamarthy commented on cmd/client/show.go
> +			if r, ok := resource.(*compute.Server); ok {
I actually came with a different fix. Review again when you get a chance.

2022-08-11 04:17 UTC, rchamarthy commented on cmd/server/register_test.go
> +	assert.NotEqual(http.StatusInternalServerError, rr.Code)
Fixed this test.

2022-08-11 04:19 UTC, rchamarthy commented
@shravyanandyala  thank you for the thorough review. I fixed all the comments, and it prompted me to look deeper into the code and find a few more bugs and fix them, and update the corresponding test cases. I know you must be enjoying your time off, so I will merge this if I don't hear from you :)

2022-08-11 08:19 UTC, shravyanandyala requested changes

2022-08-11 08:19 UTC, shravyanandyala commented on cmd/herd/pkg/labels.go
> +	codes.Add("system.group", "default")
awesome, love this change

2022-08-11 08:19 UTC, shravyanandyala commented on filestore/filestore.go
>  	// attempt to delete resource that does not exist, just return nil
just a note, we should make sure our comments are updated at some point.
maybe we should add that as a subtask for fixing docs.

2022-08-11 08:19 UTC, shravyanandyala commented on store/store_test.go
> +/*
should uncomment or delete

2022-08-11 08:19 UTC, shravyanandyala commented on store/store_test.go
should uncomment above line or delete

2022-08-11 15:52 UTC, rchamarthy commented on filestore/filestore.go
>  	// attempt to delete resource that does not exist, just return nil
Yes we should.

2022-08-11 15:59 UTC, rchamarthy commented on store/store_test.go
thank you for the catch! I dont know why we comment out test conditions. We should never do that. This caught yet another bug. Fixed it.

2022-08-11 18:54 UTC, merged