Updated the `BaseResource` type filed with a `Type` struct
project-safari/zebra pull request #123
Opened 2022-08-17 17:31 UTC by chuckluv

-updated all neccessary files that used `BaseResource`
-fixed test cases to use `Type` struct

Signed-off-by: Charles Lovett <calovett35@gmail.com>

2022-08-17 18:09 UTC, chuckluv reviewed
The lint error is saying this:
store/store.go:342:1: calculated cyclomatic complexity for function FilterProperty is 11, max is 10 (cyclop)
func FilterProperty(query zebra.Query, resMap *zebra.ResourceMap) (*zebra.ResourceMap, error) {

I'm not sure how to fix this.

2022-08-17 21:12 UTC, shravyanandyala requested changes
Looks great! I've got a few ideas on how to improve:

1. Need to update the marshal / unmarshal for ResourceMap so keys are type strings and resources don't store the type individually. It would make most sense for the key to only be a string of the type and we look up the type object internally using the resmap.go Type() func.

2. For when we unmarshal, is there any way we can remove this Type() field altogether? I'm not sure if using reflect would make sense for reducing complexity but the type field is very redundant, especially when most of the time we're working with resource maps where the key is a type string and we can use Type() to get the type object.

3. Going off of the last point, should we constrain resource maps to have Type as the key instead of a string? Seems like that's the main purpose (except the labelstore but we can just create a custom type here).

4. We should have a compare function for the Type struct and just use that instead of always doing __type__.Name() to compare. That way, if in the future the way we compare types changes, we don't have to go change a bunch of code and it's cleaner in my opinion.

2022-08-29 22:28 UTC, chuckluv commented
Not sure if it's possible to get rid of the type field since it is needed when creating the `ResourceList` that makes up the `ResourceMap`. Also, the type struct itself isn't comparable so it can't be used as a key.

2022-08-29 22:39 UTC, shravyanandyala commented
> Not sure if it's possible to get rid of the type field since it is needed when creating the `ResourceList` that makes up the `ResourceMap`. Also, the type struct itself isn't comparable so it can't be used as a key.

Haven't reviewed the new code yet but to overcome this, we can make the Type type implement the comparable interface in golang. And then we can refactor the ResourceList creation function to avoid this, it just makes the code a lot cleaner and easier for the user to not have the type littered everywhere in my opinion. Will review code now though ignoring this issue, we can circle back if we decide to do this.

2022-08-29 23:06 UTC, shravyanandyala requested changes
Sorta skimmed some of the later files -- tl;dr you don't need to pass a string in the Validate functions. Every resource has the BaseResource which has the Type field so just do resource.Type.Name() in the validate function of the resource, don't pass it to the BaseResource validate function.

2022-08-29 23:06 UTC, shravyanandyala commented on resmap.go
> +		delete(value, "type")
dead code, doesn't change the outcome.

2022-08-29 23:06 UTC, shravyanandyala commented on resmap.go
> +func CompareType(aType Type, bType Type) bool {
This is what I was talking about with a compare function but it won't work because it doesn't follow the comparable interface for golang, see here https://stackoverflow.com/questions/35101768/how-can-i-implement-comparable-interface-in-go

2022-08-29 23:06 UTC, shravyanandyala commented on store.go
> +	Delete(res Resource, types string) error
don't need this, see Validate() comment

2022-08-30 17:25 UTC, chuckluv commented
> Sorta skimmed some of the later files -- tl;dr you don't need to pass a string in the Validate functions. Every resource has the BaseResource which has the Type field so just do resource.Type.Name() in the validate function of the resource, don't pass it to the BaseResource validate function.

I am aware that every resource has a Type field however I was able to remove the type field in the Unmarshall `ResourceList` function or  at the very least set it to nil. This way since the field is empty it gets omitted like the Labels and Status fields. However because of this I needed to pass a string in the Valdiation functions in order to get them to pass. Same with the Delete function for the store.

2022-08-30 17:54 UTC, chuckluv commented on resmap.go
> +		delete(value, "type")
Not true, this remove the values in the type field before the data can be marshalled so it is not saved in the `ResourceList`. I believe this essentially removes the `Type` field since I set the field to omit if empty.

2022-08-30 17:59 UTC, chuckluv commented on cmd/herd/pkg/herd_test.go
> +	assert.Nil(user.Validate(context.Background(), user.Type.Name))
The way I currently have the code the `Type` field is not being saved after it is created so the only way to get the Type name is to pass it in.

2023-04-07 21:46 UTC, closed without merging