pluggable types
project-safari/zebra pull request #125
Opened 2022-09-12 20:16 UTC by rchamarthy

Fixes: #121

2022-09-15 18:19 UTC, shravyanandyala commented on cmd/server/api_test.go
> +	invalidRes := dc.NewLab("", "", "")
if this is a valid resource to be added, we should rename this variable since resMap.Add does not throw an error

2022-09-15 18:25 UTC, shravyanandyala commented on meta.go
> +		// Make the short ID as the defaul name
typo - default

2022-09-15 18:26 UTC, shravyanandyala commented on meta.go
> +	ModificationTime time.Time `json:"modificationTime"`
What does this mean? could we maybe add a comment for clarity

2022-09-15 18:31 UTC, shravyanandyala commented on model/dc/dc.go
>  func DataCenterType() zebra.Type {
we're considering datacenter to be one word -- this should remain consistent across the code so in keeping with that, we should change this to DatacenterType() wtih description "datacenter"

2022-09-15 20:15 UTC, shravyanandyala requested changes
CLI is broken. Can't comment on old code in show.go so I'm putting those changes here:

1. showResources is never called, either add RunE to showCmd or remove this function and disallow "zebra show" (but we really should allow this)
2. All functions must be updated to query store using their new names (i.e. "compute.esx") because right now, none of these commands work.

With these changes, the cli should work.

2022-09-16 19:28 UTC, rchamarthy commented on cmd/server/api_test.go
> +	invalidRes := dc.NewLab("", "", "")
resMap.Add does not check for the validity of the object. Its the store write that check for validity. We can make that contract change to resMap/List but that should be in a separate PR.

2022-09-16 19:29 UTC, rchamarthy commented on model/network/switch.go
> +	ManagementIP net.IP            `json:"managementIp"`
as per the tag linter this is the standard so I did change this.

2022-09-19 22:27 UTC, rchamarthy commented
@shravyanandyala I fixed all the comments from your review. Thank you for taking the time to review this large PR.

2022-09-21 17:30 UTC, chuckluv approved these changes
Aside from the change Eva suggested everything else looks good to me

2022-09-22 20:37 UTC, merged