Flex query
project-safari/zebra pull request #46
Opened 2022-07-08 21:56 UTC by shravyanandyala

Fixes #42

2022-07-09 03:39 UTC, rchamarthy requested changes

2022-07-09 03:39 UTC, rchamarthy commented on typestore/typestore.go
> +	lock      sync.RWMutex
assuming the outer store is the only way to access these specific stores for read/write we can keep these lock free and implement safety mechanisms in the outer store that will coordinate. Lets think about it.

2022-07-09 03:39 UTC, rchamarthy commented on typestore/typestore.go
> +			dest := zebra.NewResourceMap(nil)
shouldnt this get the factory from a contract pov?

2022-07-09 03:39 UTC, rchamarthy commented on typestore/typestore.go
> +	resources := zebra.NewResourceMap(nil)
this one should also get in the factory imo

2022-07-09 03:39 UTC, rchamarthy commented on typestore/typestore.go
> +	retMap := zebra.NewResourceMap(ts.resources.GetFactory())
if we are going to have lock in this store then this should have the read lock before reading the data.

2022-07-09 03:39 UTC, rchamarthy commented on typestore/typestore.go
> +		zebra.CopyResourceList(list, ts.resources.Resources[t])
assuming only the outer store will use this inner store, we should not copy the resources here, we should let the outer store do the query, apply all the filters and before doing the final return we can do the copy. That way we only copy the final result. This does mean that the internal stores cannot be accessed by anything else other the managing store.

2022-07-09 03:39 UTC, rchamarthy commented on typestore/typestore_test.go
> +	assert.True(len(resources.Resources) == 2)
use assert.Equal

2022-07-09 03:39 UTC, rchamarthy commented on typestore/typestore_test.go
> +	assert.True(len(resources.Resources) == 0)
assert.Empty

2022-07-09 03:39 UTC, rchamarthy commented on labelstore/labelstore.go
> +	uuids     map[string]zebra.Resource
why the UUID map?

2022-07-09 03:39 UTC, rchamarthy commented on labelstore/labelstore.go
> +	for label, valMap := range ls.resources {
if you have the uuid based map you can make a copy from that is much simpler. why make the resource map manually and not use the Add method on the ResourceMap. Also I noticed the ResourceMap Add takes the resource and the type string, you could get the type string from the resource.GetType so why need extra param.

2022-07-09 03:39 UTC, rchamarthy commented on labelstore/labelstore.go
> +			ls.resources[label].Delete(res, val)
if all the resources for this label are deleted we should delete the entry for the label itself. Other wise will keep hold of the bucket for this label for ever and indirectly leak memory. For example i keep create and delete labels your map will keep increasing in memory. Let me know if we need discuss this.

2022-07-09 03:39 UTC, rchamarthy commented on labelstore/labelstore.go
> +	switch query.Op {
read lock the same way if we keep the lock

2022-07-09 03:39 UTC, rchamarthy commented on labelstore/labelstore.go
> +
how about deleting from the uuids cache as well?

2022-07-09 03:39 UTC, rchamarthy commented on resourcestore/resourcestore.go
> +	retMap := zebra.NewResourceMap(rs.factory)
read lock if we keep it

2022-07-09 03:39 UTC, rchamarthy commented on store/store.go
> +	_ = rs.fs.Clear()
you should return the error if any of these substores actually return an error

2022-07-09 03:39 UTC, rchamarthy commented on store/store.go
> +	rs.fs = nil
you need to lock

2022-07-09 03:39 UTC, rchamarthy commented on store/store.go
> +	err := rs.fs.Create(res)
a little problem with transaction sematics. We need to implement. Lets finish this PR and create an issue for it. We need to implement a simple 2phase commit.

2022-07-09 04:08 UTC, shravyanandyala commented on labelstore/labelstore.go
> +			ls.resources[label].Delete(res, val)
nope I understand, oversight on my part.

2022-07-10 17:41 UTC, rchamarthy approved these changes

2022-07-11 05:45 UTC, merged