Created User Registration Api
project-safari/zebra pull request #86
Opened 2022-07-20 18:18 UTC by chuckluv

2022-07-21 01:04 UTC, shravyanandyala commented on cmd/server/register.go
> +
Actually, once you have this regData you can just call ```writeJSON(ctx, res, regData)``` and it'll do all this marshalling, header writing, etc. for you. Of course, you'd then have to either pass ctx to this func or do this in the handleRegister func.

2022-07-21 01:04 UTC, shravyanandyala commented on cmd/server/register.go
> +func createNewUser(email string, name string, key *auth.RsaIdentity, passward string) *auth.User {
small typo -- password

Also, a nitpick and completely personal preference but maybe we can reorder args to name, email, password, key. It feels more intuitive to me to have email and password next to each other but it's completely up to you whether to leave as is or change it.

2022-07-21 01:10 UTC, shravyanandyala commented on cmd/server/register.go
> +func createRole(u *auth.User, role *auth.Role) {
Maybe we can name this AssignRole()? just to avoid confusion between creating a role object and adding that role to a user.

2022-07-21 01:12 UTC, shravyanandyala commented on cmd/server/register.go
> +func deleteUser(u *auth.User, store zebra.Store) error {
Perhaps this is redundant code seeing as it does the same thing as store.Delete since User is a resource. I'm not sure though, many of these functions aren't being used so if you plan to use it in the future, leave it in.

2022-07-21 01:16 UTC, shravyanandyala commented on cmd/server/register.go
> +		Role: &auth.Role{
We should check to see if our default role should be something different -- users will initially be approved for a select group so perhaps we want to assign a default that isn't blocked from everything.

If we decide on a default, it'll be a good idea to create a DefaultRole() function in auth so we only have to change it in one place if default permissions need to change in the future.

2022-07-21 01:19 UTC, shravyanandyala commented on cmd/server/register_test.go
> +	root := "teststore1"
I think login_test.go is already using this root name, maybe change this file's default to "reg_test[insert #]" to avoid conflicts during parallel tests.

2022-07-21 02:46 UTC, rchamarthy requested changes
This is close we need few fixes and we can get this in.

2022-07-21 02:46 UTC, rchamarthy commented on cmd/server/register.go
> +
Also its better to respond with the actual auth.User object that was created as part of registration.

2022-07-21 02:46 UTC, rchamarthy commented on cmd/server/register.go
> +	none, _ := auth.NewPriv("", false, false, false, false)
lets start with giving everyone at the minimum read capability which is auth.NewPriv("", false, true, false, false)

2022-07-21 02:46 UTC, rchamarthy commented on cmd/server/register.go
> +		Role: &auth.Role{
This role should be called "user". The actual role and priv will be based on what admin will actually provide. May be admin may chose to promote a user to admin role.

2022-07-21 02:46 UTC, rchamarthy commented on cmd/server/register.go
> +func createRole(u *auth.User, role *auth.Role) {
why have a method if we are just doing an assignment to the struct field. May be I am missing something.

2022-07-21 02:46 UTC, rchamarthy commented on cmd/server/register.go
> +	rsa, err := auth.Generate()
we should never generate keys on the server side. We must always get the public key from the client and store it for our authentication purposes.

2022-07-21 14:35 UTC, chuckluv commented on cmd/server/register.go
> +		user := findUser(store, registryData.Name)
Should I change that in this PR or create a new one?

2022-07-22 13:17 UTC, chuckluv commented on cmd/server/register.go
> +func deleteUser(u *auth.User, store zebra.Store) error {
I thought the Adam needed the ability to delete a user so I left it as its own function

2022-07-22 16:14 UTC, shravyanandyala requested changes
Looks good! Minor changes just to make sure we're avoiding some bugs.

2022-07-22 16:14 UTC, shravyanandyala commented on cmd/server/login.go
> +func findUser(store zebra.Store, userName string, email string) *auth.User {
For now, let's only check email because otherwise a person could create multiple accounts with different usernames but the same email.

2022-07-22 16:14 UTC, shravyanandyala commented on cmd/server/register.go
> +func changeActiveStatus(u *auth.User, store zebra.Store, status bool) error {
What's the difference between this and delete? The function name makes it seem like you're changing u.Status.State from Active to Inactive or vice versa.

2022-07-22 16:14 UTC, shravyanandyala commented on cmd/server/login.go
>  			Name     string `json:"user"`
have to update the json tag to "name" here since you changed it to "name" somewhere else -- should be consistent across code

2022-07-22 16:49 UTC, shravyanandyala reviewed
make lint before merge

2022-07-22 17:46 UTC, shravyanandyala approved these changes

2022-07-22 21:05 UTC, rchamarthy approved these changes

2022-07-22 21:06 UTC, merged