Group Label for Zebra Resources
project-safari/zebra pull request #88
Opened 2022-07-20 21:53 UTC by evaachim

- check that all resources have the mandatory group label
- generate some sample default mandatory group label 
- create test cases 
- For Issue #71

2022-07-21 02:47 UTC, rchamarthy reviewed
Never commit binary files to git like .DS_Store or cmd/.DS_Store infact we should add these to .gitignore.

2022-07-22 20:48 UTC, shravyanandyala commented on group.go
> +
We should move this code into labels.go so all things labels are in one place.

2022-07-22 20:54 UTC, shravyanandyala requested changes

2022-07-22 20:54 UTC, shravyanandyala commented on group.go
> +
We should move this code into labels.go so all things labels are in one place. Additionally, we should update our *BaseResource Validate() function to call this labels validation before returning so we catch if our labels don't have the group key.

2022-07-22 20:54 UTC, shravyanandyala commented on group_test.go
> +func TestLabelsValidation(t *testing.T) {
Same here, this code can move to labels_test.go so all things labels are together

2022-07-22 20:54 UTC, shravyanandyala commented on cmd/herd/pkg/groupLabel.go
> +// group Value based on resource type.
I'm not sure if we want to use this group label to store the resource type (since this is already stored in the resource). Can leave as is for now, not sure what the final format for a group name will look like so we should discuss this.

2022-07-22 20:54 UTC, shravyanandyala commented on cmd/herd/pkg/groupLabel.go
> +func GroupLabels(l zebra.Labels, groupValue string) zebra.Labels {
I'm not sure we need this helper since we already have NewBaseResource(). Actually, an idea would be that we use NewBaseResource(type string, labels Labels) and check: if labels has "group" present, accept that group; otherwise, set a default group label such as "unknown". This ensures that our test code is setting group labels wherever we call NewBaseResource()

2022-07-23 05:45 UTC, shravyanandyala commented on group.go
> +
Ok, if we take this to be a special case of labels, then we don't need this function. Just do the validation for group label in BaseResource validation. Let's not litter the code base with unnecessary files.

2022-07-23 05:49 UTC, shravyanandyala commented on cmd/herd/pkg/groupLabel.go
> +// group Value based on resource type.
I think there's a misunderstanding of what the group label is for. First, labels are exclusive, only one value per key. Group captures connectivity -- all resources in a particular group have a specific level of connectivity. It is not for type. We can discuss this more to further clarify need be.

2022-07-23 17:24 UTC, rchamarthy requested changes
Remove group.go and group_test.go and add the validation function to resoure.go and call it in BaseResource.Validate.

The important part we need is that every Generate* function in herd/pkg that is generating these resources must add the label so that its generating valid resources. I suggest we pick say 5 group values and randomly select one value per resource while generating that specific resource. Every resource generated MUST have the group label with a value. This way when UI uses this data they can also do label selection per group.

2022-07-23 17:24 UTC, rchamarthy commented on cmd/herd/pkg/group_label.go
> +	groupValue := resource.GetType()
We will never a have a group value per type. For example we will have all types of resources like switchs, servers, racks that belong to one group say building15 be labeled as "group=building15". So type specific groups wont exist.

2022-07-23 17:24 UTC, rchamarthy commented on group.go
> +func (l Labels) Validate() error {
Labels do not specify this constraint. Meaning every label doesn't have to have a mandatory kv called "group=xxx". But every label set that is added to a resource MUST have a group. For example tomorrow I can create a structure for leases or other types which are not resources but want to have labels. Then those resources will also get the constraint of having a group label. This validation should be done BaseResource which enforces the contract of having a label for all resources.

2022-07-27 15:11 UTC, merged