Created `Secret` type struct
project-safari/zebra pull request #89
Opened 2022-07-21 00:18 UTC by chuckluv

2022-07-21 00:49 UTC, shravyanandyala requested changes

2022-07-21 00:49 UTC, shravyanandyala commented on secret.go
> +type Secret struct {
If this struct only contains a string, we can just make it a type string
```
type Secret string
```

2022-07-21 00:49 UTC, shravyanandyala commented on secret.go
> +func (s *Secret) UnmarshalText(text []byte) error {
If we choose to use ```type Secret string```, we actually don't even need this because json.Unmarshal will figure it out for us.

2022-07-21 02:35 UTC, rchamarthy commented on secret.go
> +type Secret struct {
right now its just string but we may add some hash algorithm etc to this down the line so ok to be a struct.

2022-07-21 02:36 UTC, rchamarthy commented on secret.go
> +func (s *Secret) UnmarshalText(text []byte) error {
Yes but struct may be required for potential encryption and hashing. Should be ok for now as its trivial to unmarshal as such.

2022-07-21 02:38 UTC, rchamarthy approved these changes
@chuckluv Lets add a commit that will make the auth.User PasswordHash and Key fields to be of type Secret.

2022-07-22 21:05 UTC, shravyanandyala approved these changes

2022-07-22 22:05 UTC, merged